spring.jpa:
  hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  url: jdbc:mariadb://localhost:3306/user
  username: user
  password: password
  platform: mariadb
  driver-class-name: org.mariadb.jdbc.Driver
  hikari.maximum-pool-size: 20

jwt:
  secret-key: login-appllication-2022-12-25.secret_key
  token.expired-time-ms: 2592000000